#!/bin/bash
# mount -o bind /sdcard /root/sdcard
modprobe usb_f_fs
modprobe usb_f_mtp
modprobe usb_f_ptp
modprobe libcomposite
mkdir /sys/kernel/config/usb_gadget/g1
cd /sys/kernel/config/usb_gadget/g1

#Set default Vendor and Product IDs for now
echo 0x18d1 > idVendor
echo 0x4E26 > idProduct

#Create English strings and add random deviceID
mkdir strings/0x409
echo 0123459876 > strings/0x409/serialnumber

#Update following if you want to
echo "Test" > strings/0x409/manufacturer
echo "Test" > strings/0x409/product

#Create gadget configuration
mkdir configs/c.1
mkdir configs/c.1/strings/0x409
echo "CDC ACM + MTP + Mass Storage" > configs/c.1/strings/0x409/configuration
echo 120 > configs/c.1/MaxPower

echo "Creating ACM interface"
mkdir functions/acm.GS0
ln -s functions/acm.GS0 configs/c.1
#    Make sure we create MTP function and add (symlink) it in gadget configuration only when the Android boot is complete. You can check that by checking the status of sys.boot_completed property before running the following commands.

#Create MTP function,
#And link it to the gadget configuration
mkdir /sys/kernel/config/usb_gadget/g1/functions/mtp.mtp
ln -s /sys/kernel/config/usb_gadget/g1/functions/mtp.mtp /sys/kernel/config/usb_gadget/g1/configs/c.1/mtp.mtp
mkdir /dev/mtp
# mount -t functionfs mtp /dev/mtp

echo "Creating Mass Storage interface"
mkdir functions/mass_storage.ms0
echo "/dev/mmcblk0" > functions/mass_storage.ms0/lun.0/file
echo "1" > functions/mass_storage.ms0/lun.0/removable
ln -s functions/mass_storage.ms0 configs/c.1/mass_storage.ms0

#Enable the Gadget      echo `ls /sys/class/udc` > UDC
#Replace "ci_hdrc.0" with your platform UDC driver as found in /sys/class/udc/
echo `ls /sys/class/udc` > /sys/kernel/config/usb_gadget/g1/UDC
mtp-server &
getty ttyGS0 115200 linux &
