#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postrm.d && run-parts --arg="4.14.8-16ton-full+" --arg="/boot/vmlinuz-4.14.8-16ton-full+" /etc/kernel/postrm.d
exit 0
