#!/bin/sh
# Copyright (C) 2004-2005 Intel Corporation
#
count=0
while true; do
	count=$((count+1))
	clear
	echo $count
	./load
	sleep 1
	echo $count `date` > output
	dmesg -c >> output
	iwconfig
	sleep 1
	if grep "probe.*failed" output; then break; fi
done
