src = /home/maddocks/kernels/zfs/module/spl

MODULE := spl

obj-$(CONFIG_ZFS) := $(MODULE).o

ccflags-y := $(ZFS_MODULE_CFLAGS) $(ZFS_MODULE_CPPFLAGS)


-include /home/maddocks/kernels/zfs/module/os/linux/spl/Makefile
